server:
  port: 8080
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/mybatis
     username: root
     password: linhuanshu
     driver-class-name: com.mysql.jdbc.Driver
logging:
  level: debug
mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
